version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: shortener_postgres
    environment:
      POSTGRES_DB: shortener_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
