"""03_changed_pk

Revision ID: 3ed05608e378
Revises: 3f998712e23c
Create Date: 2023-09-25 18:00:16.009930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed05608e378'
down_revision: Union[str, None] = '3f998712e23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'original_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('url', 'short_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.create_unique_constraint(None, 'url', ['short_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    op.alter_column('url', 'short_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('url', 'original_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###
