"""02_added_url_fields

Revision ID: 3f998712e23c
Revises: 3de7663b44b3
Create Date: 2023-09-25 17:05:07.653831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f998712e23c'
down_revision: Union[str, None] = '3de7663b44b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('short_url', sa.String(length=1024), nullable=True))
    op.add_column('url', sa.Column('number_of_visits', sa.Integer(), nullable=True))
    op.drop_constraint('url_original_url_key', 'url', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('url_original_url_key', 'url', ['original_url'])
    op.drop_column('url', 'number_of_visits')
    op.drop_column('url', 'short_url')
    # ### end Alembic commands ###
