"""04_visit_table

Revision ID: f5faae5208ff
Revises: 3ed05608e378
Create Date: 2023-09-25 18:55:52.296459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5faae5208ff'
down_revision: Union[str, None] = '3ed05608e378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('user_ip', sa.String(length=1024), nullable=False),
    sa.Column('visit_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_id'), 'visit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_id'), table_name='visit')
    op.drop_table('visit')
    # ### end Alembic commands ###
